version: '3'
services:
  eth-stats:
    image: quay.io/maicoin/eth-netstats:latest
    ports:
      - '3000:3000'
    environment:
      - WS_SECRET=bb98a0b6442386d0cdf8a31b267892c1
    networks:
      app_net:
          ipv4_address: 172.16.238.9
  validator-01:
    hostname: validator-01
    image: quay.io/amis/quorum:demo
    ports:
      - '30303:30303'
    environment:
      - IDENTITY=validator-01
      - NODEKEY=1862cf0b92e8da1c92521006f29a5a9cca33ee7537a23112719c41bf816832f2
      - BOOTNODES=enode://52870b1bb7874e4ebffd708fbdea7add773912c000e54e5b504ea01ecd956ecb2b54ea4b2076fcfbd24121209dfe97ca8b6368926ce1956e53f63fd20c0e29d7@172.16.238.10:30303,enode://c8fa7bd31ac2bd271fbbc7c5503bff29a94b8301bac5fa5ab7e8787672febc0541926dcb5d8698ef36e66ccba84ef071ee1d29f9aebc9e6bbf4cfeb4e4dce8ad@172.16.238.11:30304,enode://a5a6c556e7ac360e8f2eee5d03c11f447c3d918d73692958695b429b9f0d67fbcb817aea2c169d7abd5a80bbae2adf6bf7e0237c8f78d93d6a82a27efe12ec57@172.16.238.12:30305,enode://5cd6270a6317e8bb1c8a70e5041260ae2864dc35103d27e129c6b0f9cf657cf3db866199a528b33d0ffb48f4e71b1ec8a01102e753cd527afa9c2ba3dfd4515d@172.16.238.13:30306
      - PORT=30303
      - ETHSTATS=bb98a0b6442386d0cdf8a31b267892c1@172.16.238.9:3000
    networks:
      app_net:
          ipv4_address: 172.16.238.10
  validator-02:
    image: quay.io/amis/quorum:demo
    ports:
      - '30304:30304'
    environment:
      - IDENTITY=validator-02
      - NODEKEY=72fa6fc77e8ea98a5adc168c0ceed63205d9580dcbb969df794248dee5a00ea5
      - BOOTNODES=enode://52870b1bb7874e4ebffd708fbdea7add773912c000e54e5b504ea01ecd956ecb2b54ea4b2076fcfbd24121209dfe97ca8b6368926ce1956e53f63fd20c0e29d7@172.16.238.10:30303,enode://c8fa7bd31ac2bd271fbbc7c5503bff29a94b8301bac5fa5ab7e8787672febc0541926dcb5d8698ef36e66ccba84ef071ee1d29f9aebc9e6bbf4cfeb4e4dce8ad@172.16.238.11:30304,enode://a5a6c556e7ac360e8f2eee5d03c11f447c3d918d73692958695b429b9f0d67fbcb817aea2c169d7abd5a80bbae2adf6bf7e0237c8f78d93d6a82a27efe12ec57@172.16.238.12:30305,enode://5cd6270a6317e8bb1c8a70e5041260ae2864dc35103d27e129c6b0f9cf657cf3db866199a528b33d0ffb48f4e71b1ec8a01102e753cd527afa9c2ba3dfd4515d@172.16.238.13:30306
      - PORT=30304
      - ETHSTATS=bb98a0b6442386d0cdf8a31b267892c1@172.16.238.9:3000
    networks:
      app_net:
        ipv4_address: 172.16.238.11
    links:
        - validator-01
        - validator-03
        - validator-04
  validator-03:
    image: quay.io/amis/quorum:demo
    ports:
      - '30305:30305'
    environment:
      - IDENTITY=validator-03
      - NODEKEY=31f07e972131b6449296d519a99b0b6a4b58426f3a56093174601475efd5c944
      - BOOTNODES=enode://52870b1bb7874e4ebffd708fbdea7add773912c000e54e5b504ea01ecd956ecb2b54ea4b2076fcfbd24121209dfe97ca8b6368926ce1956e53f63fd20c0e29d7@172.16.238.10:30303,enode://c8fa7bd31ac2bd271fbbc7c5503bff29a94b8301bac5fa5ab7e8787672febc0541926dcb5d8698ef36e66ccba84ef071ee1d29f9aebc9e6bbf4cfeb4e4dce8ad@172.16.238.11:30304,enode://a5a6c556e7ac360e8f2eee5d03c11f447c3d918d73692958695b429b9f0d67fbcb817aea2c169d7abd5a80bbae2adf6bf7e0237c8f78d93d6a82a27efe12ec57@172.16.238.12:30305,enode://5cd6270a6317e8bb1c8a70e5041260ae2864dc35103d27e129c6b0f9cf657cf3db866199a528b33d0ffb48f4e71b1ec8a01102e753cd527afa9c2ba3dfd4515d@172.16.238.13:30306
      - PORT=30305
      - ETHSTATS=bb98a0b6442386d0cdf8a31b267892c1@172.16.238.9:3000
    networks:
      app_net:
        ipv4_address: 172.16.238.12
    links:
        - validator-01
  validator-04:
    image: quay.io/amis/quorum:demo
    ports:
      - '30306:30306'
    environment:
      - IDENTITY=validator-04
      - NODEKEY=4b67c5a38c067a477088b2d2607dbec6ce2b2febcba9fe64bc27ee81e4f34532
      - BOOTNODES=enode://52870b1bb7874e4ebffd708fbdea7add773912c000e54e5b504ea01ecd956ecb2b54ea4b2076fcfbd24121209dfe97ca8b6368926ce1956e53f63fd20c0e29d7@172.16.238.10:30303,enode://c8fa7bd31ac2bd271fbbc7c5503bff29a94b8301bac5fa5ab7e8787672febc0541926dcb5d8698ef36e66ccba84ef071ee1d29f9aebc9e6bbf4cfeb4e4dce8ad@172.16.238.11:30304,enode://a5a6c556e7ac360e8f2eee5d03c11f447c3d918d73692958695b429b9f0d67fbcb817aea2c169d7abd5a80bbae2adf6bf7e0237c8f78d93d6a82a27efe12ec57@172.16.238.12:30305,enode://5cd6270a6317e8bb1c8a70e5041260ae2864dc35103d27e129c6b0f9cf657cf3db866199a528b33d0ffb48f4e71b1ec8a01102e753cd527afa9c2ba3dfd4515d@172.16.238.13:30306
      - PORT=30306
      - ETHSTATS=bb98a0b6442386d0cdf8a31b267892c1@172.16.238.9:3000
    networks:
        app_net:
          ipv4_address: 172.16.238.13
    links:
        - validator-01
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24